version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - "5432:5432"
  web:
    build: .
    # command: hanami server --host=0.0.0.0
    command: tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "2300:2300"
    depends_on:
      - db
